-- File: C:/Users/student/Documents/MSDC/out/vhdl/cezar.vhd
-- Generated by MyHDL 0.10
-- Date: Mon Dec  3 17:34:47 2018


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_010.all;

entity cezar is
    port (
        clk: in std_logic;
        reset: in std_logic;
        state: in std_logic;
        key: in std_logic;
        out_tdata: inout unsigned(31 downto 0);
        out_tready: in std_logic;
        out_tvalid: out std_logic;
        out_tlast: out std_logic;
        message_tdata: in unsigned(31 downto 0);
        message_tready: in std_logic;
        message_tvalid: in std_logic;
        message_tlast: in std_logic
    );
end entity cezar;


architecture MyHDL of cezar is



begin




CEZAR_CEZAR_PROC: process (clk) is
begin
    if rising_edge(clk) then
        if (reset = '0') then
            out_tlast <= '0';
            out_tdata <= to_unsigned(0, 32);
            out_tvalid <= '0';
        else
            out_tvalid <= '0';
            out_tlast <= '0';
            out_tdata <= Signal(unsigned'("00000000000000000000000000000000"));
            case state is
                when '1' =>
                    out_tdata <= (message_tdata + to_unsigned(key, 1));
                    if (out_tdata > 15) then
                        out_tdata <= (0 + to_unsigned(key, 32));
                    elsif (out_tdata < 0) then
                        out_tdata <= (15 + to_unsigned(key, 32));
                    end if;
                when '0' =>
                    out_tdata <= (message_tdata - to_unsigned(key, 1));
                    if (out_tdata > 15) then
                        out_tdata <= (0 - to_unsigned(key, 32));
                    elsif (out_tdata < 0) then
                        out_tdata <= (15 - to_unsigned(key, 32));
                    end if;
                when others =>
                    assert False report "End of Simulation" severity Failure;
            end case;
        end if;
    end if;
end process CEZAR_CEZAR_PROC;

end architecture MyHDL;
