-- File: D:/Desktop/Explorer/Mateusz/Studia/Semestr 7/ESL/MSDC/out/vhdl\cezar.vhd
-- Generated by MyHDL 0.10
-- Date: Thu Dec 13 17:45:19 2018


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_010.all;

entity cezar is
    port (
        clk: in std_logic;
        reset: in std_logic;
        state: in std_logic;
        key: in unsigned(3 downto 0);
        out_tdata: out unsigned(31 downto 0);
        out_tready: in std_logic;
        out_tvalid: in std_logic;
        out_tlast: in std_logic;
        message_tdata: in unsigned(31 downto 0);
        message_tready: in std_logic;
        message_tvalid: in std_logic;
        message_tlast: in std_logic
    );
end entity cezar;


architecture MyHDL of cezar is



begin




CEZAR_CEZAR_PROC: process (clk) is
begin
    if rising_edge(clk) then
        if (reset = '0') then
            out_tdata <= to_unsigned(0, 32);
        else
            case state is
                when '1' =>
                    out_tdata <= (message_tdata + key);
                when '0' =>
                    out_tdata <= (message_tdata - key);
                when others =>
                    assert False report "End of Simulation" severity Failure;
            end case;
        end if;
    end if;
end process CEZAR_CEZAR_PROC;

end architecture MyHDL;
